name: Java â€“ choose Main

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      mainClass:
        description: "Which main class to run"
        type: choice
        options:
          - org.example.Main
          - org.example.Main2
        default: org.example.Main

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      # default when the run was triggered by push (no inputs available)
      MAIN_CLASS: ${{ github.event_name == 'workflow_dispatch' && inputs.mainClass || 'org.example.Main' }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'


      - name: Compile all sources
        run: javac $(find src/main/java -name "*.java")

      - name: Run selected main
        run: java -cp src/main/java $MAIN_CLASS

      - name: Compile Java program
        run: javac src/main/java/org/example/Main.java

      - name: Run Java program
        run: java -cp src/main/java org.example.Main

